2014/10/27 13:14:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "login".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/yii/ycrm/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/ycrm/index.php?r=site/page&view=about
HTTP_REFERER=http://localhost:8081/yii/ycrm/index.php?r=site/contact
---
2014/10/27 15:26:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index.php".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('index.php')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('index.php')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/index.php/...')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/yii/ycrm/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/ycrm/index.php/site/index.php/gii
---
2014/10/27 16:48:55 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] FATAL:  could not open relation mapping file "global/pg_filenode.map": Permission denied
FATAL:  could not open relation mapping file "global/pg_filenode.map": Permission denied' in /var/www/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /var/www/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /var/www/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /var/www/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /var/www/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /var/www/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /var/www/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /var/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /var/www/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/yii/ycrm/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/ycrm/index.php/gii/model/index
HTTP_REFERER=http://localhost:8081/yii/ycrm/index.php/gii/default/index
---
2014/10/27 16:52:57 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] FATAL:  could not open relation mapping file "global/pg_filenode.map": Permission denied
FATAL:  could not open relation mapping file "global/pg_filenode.map": Permission denied' in /var/www/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /var/www/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /var/www/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /var/www/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /var/www/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /var/www/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /var/www/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /var/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /var/www/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/yii/ycrm/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/ycrm/index.php/gii/model/index
HTTP_REFERER=http://localhost:8081/yii/ycrm/index.php/gii/default/index
---
2014/10/27 16:53:06 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] FATAL:  could not open relation mapping file "global/pg_filenode.map": Permission denied
FATAL:  could not open relation mapping file "global/pg_filenode.map": Permission denied' in /var/www/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /var/www/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /var/www/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /var/www/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /var/www/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /var/www/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /var/www/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /var/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /var/www/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/yii/ycrm/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/ycrm/index.php/gii/model/index
HTTP_REFERER=http://localhost:8081/yii/ycrm/index.php/gii/controller/index
---
2014/10/27 16:56:20 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] FATAL:  could not open relation mapping file "global/pg_filenode.map": Permission denied
FATAL:  could not open relation mapping file "global/pg_filenode.map": Permission denied' in /var/www/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /var/www/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /var/www/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /var/www/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /var/www/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /var/www/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /var/www/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /var/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /var/www/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/yii/ycrm/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/ycrm/index.php/gii/model/index
HTTP_REFERER=http://localhost:8081/yii/ycrm/index.php/gii/controller/index
---
2014/10/27 16:56:22 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] FATAL:  could not open relation mapping file "global/pg_filenode.map": Permission denied
FATAL:  could not open relation mapping file "global/pg_filenode.map": Permission denied' in /var/www/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /var/www/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /var/www/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /var/www/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /var/www/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /var/www/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /var/www/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /var/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /var/www/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/yii/ycrm/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/ycrm/index.php/gii/model/index
HTTP_REFERER=http://localhost:8081/yii/ycrm/index.php/gii/controller/index
---
2014/10/27 16:56:22 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] FATAL:  could not open relation mapping file "global/pg_filenode.map": Permission denied
FATAL:  could not open relation mapping file "global/pg_filenode.map": Permission denied' in /var/www/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /var/www/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /var/www/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /var/www/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /var/www/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /var/www/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /var/www/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /var/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /var/www/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/yii/ycrm/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/ycrm/index.php/gii/model/index
HTTP_REFERER=http://localhost:8081/yii/ycrm/index.php/gii/controller/index
---
2014/10/27 16:56:22 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] FATAL:  could not open relation mapping file "global/pg_filenode.map": Permission denied
FATAL:  could not open relation mapping file "global/pg_filenode.map": Permission denied' in /var/www/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /var/www/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /var/www/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /var/www/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /var/www/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /var/www/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /var/www/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /var/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /var/www/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/yii/ycrm/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/ycrm/index.php/gii/model/index
HTTP_REFERER=http://localhost:8081/yii/ycrm/index.php/gii/controller/index
---
2014/10/27 16:56:23 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] FATAL:  could not open relation mapping file "global/pg_filenode.map": Permission denied
FATAL:  could not open relation mapping file "global/pg_filenode.map": Permission denied' in /var/www/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /var/www/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /var/www/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /var/www/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /var/www/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /var/www/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /var/www/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /var/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /var/www/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/yii/ycrm/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/ycrm/index.php/gii/model/index
HTTP_REFERER=http://localhost:8081/yii/ycrm/index.php/gii/controller/index
---
2014/10/27 16:56:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "login".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/yii/ycrm/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/ycrm/
HTTP_REFERER=http://localhost:8081/yii/
---
2014/10/27 16:56:47 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] FATAL:  could not open relation mapping file "global/pg_filenode.map": Permission denied
FATAL:  could not open relation mapping file "global/pg_filenode.map": Permission denied' in /var/www/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /var/www/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /var/www/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /var/www/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /var/www/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /var/www/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /var/www/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /var/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /var/www/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/yii/ycrm/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/ycrm/index.php/gii/model/index
HTTP_REFERER=http://localhost:8081/yii/ycrm/index.php/gii/controller/index
---
2014/10/27 17:33:42 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] FATAL:  could not open relation mapping file "global/pg_filenode.map": Permission denied
FATAL:  could not open relation mapping file "global/pg_filenode.map": Permission denied' in /var/www/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /var/www/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /var/www/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /var/www/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /var/www/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /var/www/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /var/www/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /var/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /var/www/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/yii/ycrm/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/ycrm/index.php/gii/model/index
HTTP_REFERER=http://localhost:8081/yii/ycrm/index.php/gii/controller/index
---
2014/10/27 17:34:10 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] FATAL:  could not open relation mapping file "global/pg_filenode.map": Permission denied
FATAL:  could not open relation mapping file "global/pg_filenode.map": Permission denied' in /var/www/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /var/www/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /var/www/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /var/www/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /var/www/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /var/www/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /var/www/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /var/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /var/www/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/yii/ycrm/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/ycrm/index.php/gii/model/index
---
2014/10/27 17:34:23 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[08006] [7] FATAL:  could not open relation mapping file "global/pg_filenode.map": Permission denied
FATAL:  could not open relation mapping file "global/pg_filenode.map": Permission denied' in /var/www/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /var/www/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /var/www/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /var/www/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /var/www/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /var/www/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /var/www/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /var/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /var/www/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/yii/ycrm/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/ycrm/index.php/gii/model/index
HTTP_REFERER=http://localhost:8081/yii/ycrm/index.php/gii/controller/index
---
2014/10/28 00:12:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "login".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/yii/ycrm/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/ycrm/
HTTP_REFERER=http://localhost:8081/yii/
---
